"""Create GitHub Issues for new top job matches."""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone

import requests

logger = logging.getLogger(__name__)

_GH_API = "https://api.github.com"

_TIER_LABELS = {
    1: ("tier-1-apply-now",  "00aa00", "Score ≥80 — Apply Immediately"),
    2: ("tier-2-apply-soon", "ddaa00", "Score 65–79 — Apply Soon"),
    3: ("tier-3-consider",   "0075ca", "Score 50–64 — Worth Considering"),
}
_TIER_ICONS = {1: "🚀", 2: "⚡", 3: "🔍"}
_GO_LABELS  = {"apply": "✅ GO", "maybe": "⚠️ MAYBE", "skip": "❌ SKIP"}


def _headers() -> dict:
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise EnvironmentError("GITHUB_TOKEN not set — cannot create GitHub Issues")
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _repo() -> str:
    repo = os.getenv("GITHUB_REPO")
    if not repo:
        raise EnvironmentError("GITHUB_REPO not set (expected format: owner/repo)")
    return repo


# ── Label setup ───────────────────────────────────────────────────────────────

def ensure_labels(repo: str) -> None:
    """Create required labels in the repo if they don't already exist."""
    all_labels = [
        ("job-match", "1d76db", "AI-matched job from rolesearch"),
        *[(name, color, desc) for name, color, desc in _TIER_LABELS.values()],
    ]
    for name, color, desc in all_labels:
        try:
            requests.post(
                f"{_GH_API}/repos/{repo}/labels",
                headers=_headers(),
                json={"name": name, "color": color, "description": desc},
                timeout=10,
            )
        except Exception as exc:
            logger.debug("Label '%s' may already exist: %s", name, exc)


# ── Deduplication ─────────────────────────────────────────────────────────────

def issue_already_exists(repo: str, job_id: str) -> bool:
    """Check open issues for this job_id to avoid duplicates on DB cache miss."""
    try:
        resp = requests.get(
            f"{_GH_API}/repos/{repo}/issues",
            headers=_headers(),
            params={"state": "open", "labels": "job-match", "per_page": 100},
            timeout=10,
        )
        if resp.status_code != 200:
            return False
        for issue in resp.json():
            if job_id in issue.get("body", ""):
                return True
    except Exception as exc:
        logger.warning("Could not check existing issues: %s", exc)
    return False


# ── Issue body ────────────────────────────────────────────────────────────────

def _build_body(match: dict, repo: str) -> str:
    rank     = match.get("priority_rank") or 3
    rec      = match.get("recommendation", "maybe")
    score    = match["score"]
    icon     = _TIER_ICONS.get(rank, "🔍")
    decision = _GO_LABELS.get(rec, rec.upper())

    key_matches = json.loads(match["key_matches"]) if isinstance(match["key_matches"], str) else match["key_matches"]
    gaps        = json.loads(match["gaps"])        if isinstance(match["gaps"], str)        else match["gaps"]

    matches_md = "\n".join(f"- {m}" for m in key_matches) or "- —"
    gaps_md    = "\n".join(f"- {g}" for g in gaps)        or "- None identified"

    age_line = ""
    if match.get("posted_at"):
        try:
            from src.validator import _parse_date
            dt = _parse_date(match["posted_at"])
            if dt:
                d = (datetime.now(tz=timezone.utc) - dt).days
                age_line = f" · Posted **{d} days ago**"
        except Exception:
            pass

    salary_md = f"**{match['salary']}**" if match.get("salary") else "_Not listed_"
    source    = match.get("source", "").title()
    job_id    = match["job_id"]

    tier_name = {1: "APPLY IMMEDIATELY", 2: "APPLY SOON", 3: "WORTH CONSIDERING"}.get(rank, "")

    return f"""\
## {icon} Tier {rank} — {tier_name}

| Field | Detail |
|---|---|
| **Score** | {score} / 100 |
| **Decision** | {decision} |
| **Location** | {match['location']}{age_line} |
| **Salary** | {salary_md} |
| **Source** | {source} |

---

### Executive Summary
{match.get('executive_summary') or '_Not available_'}

---

### Key Matches
{matches_md}

### Gaps
{gaps_md}

---

### Next Steps

**Apply:** {match.get('url') or '_URL not available_'}

**Generate tailored resume + cover letter locally:**
```bash
python main.py generate {job_id}
```

**Job ID:** `{job_id}`

---
<sub>Generated by [rolesearch](https://github.com/{repo}) · AI-powered job search agent</sub>
"""


# ── Public entry point ────────────────────────────────────────────────────────

def create_issue(match: dict) -> str | None:
    """
    Open a GitHub Issue for a job match.
    Returns the issue URL on success, None on failure.
    """
    repo  = _repo()
    rank  = match.get("priority_rank") or 3
    score = match["score"]
    icon  = _TIER_ICONS.get(rank, "🔍")

    title = f"{icon} [Score: {score}] {match['title']} @ {match['company']}"
    body  = _build_body(match, repo)
    labels = ["job-match", _TIER_LABELS[rank][0]]

    try:
        resp = requests.post(
            f"{_GH_API}/repos/{repo}/issues",
            headers=_headers(),
            json={"title": title, "body": body, "labels": labels},
            timeout=15,
        )
        if resp.status_code == 201:
            url = resp.json().get("html_url", "")
            logger.info("Issue created: %s", url)
            return url
        logger.error("Issue creation failed %s: %s", resp.status_code, resp.text[:300])
    except Exception as exc:
        logger.error("Issue creation exception: %s", exc)
    return None


def notify_new_matches(matches: list[dict]) -> int:
    """
    Create GitHub Issues for a list of matches.
    Skips any that already have an open issue (dedup by job_id in body).
    Returns count of issues created.
    """
    if not matches:
        return 0

    repo = _repo()
    try:
        ensure_labels(repo)
    except Exception as exc:
        logger.warning("Could not ensure labels: %s", exc)

    created = 0
    for match in matches:
        job_id = match["job_id"]
        if issue_already_exists(repo, job_id):
            logger.info("Issue already exists for %s — skipping", job_id[:8])
            continue
        url = create_issue(match)
        if url:
            created += 1
            print(f"  Issue opened: {url}")
    return created
